package ru.hse.edu.locallense.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF0078E8)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFD9E7FF)
val onPrimaryContainerLight = Color(0xFF001B3D)
val secondaryLight = Color(0xFF007A5A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB2F1D8)
val onSecondaryContainerLight = Color(0xFF002117)
val tertiaryLight = Color(0xFF9553F6)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFECDDFF)
val onTertiaryContainerLight = Color(0xFF2E0068)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF5FAFC)
val onBackgroundLight = Color(0xFF141C1F)
val surfaceLight = Color(0xFFF5FAFC)
val onSurfaceLight = Color(0xFF141C1F)

val surfaceVariantLight = Color(0xFFDCE4E8)
val onSurfaceVariantLight = Color(0xFF40484C)
val outlineLight = Color(0xFF70787D)
val outlineVariantLight = Color(0xFFC0C8CC)

val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF293134)
val inverseOnSurfaceLight = Color(0xFFEBF2F5)
val inversePrimaryLight = Color(0xFFA8C9FF)

val surfaceDimLight = Color(0xFFD4DCE0)
val surfaceBrightLight = Color(0xFFF5FAFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF4F7)
val surfaceContainerLight = Color(0xFFE9EFF2)
val surfaceContainerHighLight = Color(0xFFE3E9EC)
val surfaceContainerHighestLight = Color(0xFFDDE3E6)

val primaryDark = Color(0xFFAAC7FF)
val onPrimaryDark = Color(0xFF0A305F)
val primaryContainerDark = Color(0xFF284777)
val onPrimaryContainerDark = Color(0xFFD6E3FF)
val secondaryDark = Color(0xFFBEC6DC)
val onSecondaryDark = Color(0xFF283141)
val secondaryContainerDark = Color(0xFF3E4759)
val onSecondaryContainerDark = Color(0xFFDAE2F9)
val tertiaryDark = Color(0xFFDDBCE0)
val onTertiaryDark = Color(0xFF3F2844)
val tertiaryContainerDark = Color(0xFF573E5C)
val onTertiaryContainerDark = Color(0xFFFAD8FD)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF111318)
val onBackgroundDark = Color(0xFFE2E2E9)
val surfaceDark = Color(0xFF111318)
val onSurfaceDark = Color(0xFFE2E2E9)
val surfaceVariantDark = Color(0xFF44474E)
val onSurfaceVariantDark = Color(0xFFC4C6D0)
val outlineDark = Color(0xFF8E9099)
val outlineVariantDark = Color(0xFF44474E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E9)
val inverseOnSurfaceDark = Color(0xFF2E3036)
val inversePrimaryDark = Color(0xFF415F91)
val surfaceDimDark = Color(0xFF111318)
val surfaceBrightDark = Color(0xFF37393E)
val surfaceContainerLowestDark = Color(0xFF0C0E13)
val surfaceContainerLowDark = Color(0xFF191C20)
val surfaceContainerDark = Color(0xFF1D2024)
val surfaceContainerHighDark = Color(0xFF282A2F)
val surfaceContainerHighestDark = Color(0xFF33353A)